apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass          # generated before in secret.yml
                key: password
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
          - name: wordpress-storage
            mountPath: "/var/www/html"          # which data will be stored
